<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2JDsKvh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2JDsKvh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2JDsKvh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2JDsKvh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2JDsKvh\App_KernelDevDebugContainer([
    'container.build_hash' => '2JDsKvh',
    'container.build_id' => '83f056b8',
    'container.build_time' => 1665679672,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2JDsKvh');
